[tox]
env_list = py310, docs, coverage

[gh-actions]
python =
    3.10: py310, docs

[testenv]
basepython =
    {py310,docs,coverage}: python3.10
setenv =
    PYTHONUNBUFFERED = yes
passenv =
    *
extras =
    test
commands =
    pytest
usedevelop = true

[testenv:docs]
description = build HTML docs
setenv =
    READTHEDOCS_PROJECT = chemecho
    READTHEDOCS_VERSION = latest
extras =
    doc
commands =
    sphinx-build -d "{toxworkdir}/docs_doctree" docs/source "docs/docs_out"

[testenv:coverage]
commands =
    pytest --cov=src/chemecho --cov-report xml:.tox/coverage.xml --cov-report term
    genbadge coverage -i .tox/coverage.xml -o assets/coverage-badge.svg