# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 08e8b92
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: null
author_name: null
github_org: ynhchoi
package_name: chemecho
project_name: chemecho
short_description: null
